name: Deploy FastAPI to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout the code from your repository
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    # Step 2: Set up a Python environment
    - name: 'Set up Python 3.9'
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip'
        cache-dependency-path: 'backend/requirements.txt'

    - name: 'Install dependencies'
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
    
    # Step 3: Log in to Azure and deploy the application
    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: 'Deploy to Azure App Service'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Nexora'
        slot-name: 'production'
        package: '.'
        startup-command: 'uvicorn backend.main:app --host 0.0.0.0 --port 80'
