name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Render CLI
        run: |
          curl -fsSL https://cdn.render.com/cli/latest/install.sh | bash
          export PATH=$HOME/.render/bin:$PATH
          render --version

      - name: Trigger deploy on Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          export PATH=$HOME/.render/bin:$PATH
          render services deploy srv-d3374e3uibrs73ac3kk0
