name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Trigger deploy via Render API
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          echo "Triggering deploy on Render service srv-d3374e3uibrs73ac3kk0..."
          response=$(curl -s -o /dev/null -w "%{http_code}" -X POST "https://api.render.com/deploy/srv-d3374e3uibrs73ac3kk0" \
            -H "Accept: application/json" \
            -H "Authorization: Bearer $RENDER_API_KEY")

          if [ "$response" -eq 201 ]; then
            echo "Deploy triggered successfully."
          else
            echo "Failed to trigger deploy. HTTP status code: $response"
            exit 1
          fi
